init:
  - echo %PATH%
  # We use a clean PATH to avoid interferences with the hundreds of installed programs.
  - set PATH=c:/Program Files/Git/cmd;c:/ProgramData/chocolatey/bin;c:/Program Files (x86)/Inno Setup 5;c:/Windows/system32;C:/Windows/System32/WindowsPowerShell/v1.0

build_script:
  - set PATH=C:/ruby24-x64/bin;%PATH%

after_test:
  - ridk version
  - ridk enable
  - IF DEFINED APPVEYOR_REPO_TAG_NAME (
    set DEPLOY_TAG=%APPVEYOR_REPO_TAG_NAME% &
    c:/msys64/usr/bin/mkdir -p /home/appveyor/.gnupg &&
    gpg --passphrase %GPGPASSWD% --decrypt appveyor-key.asc.asc | gpg --import &&
    gpg --detach-sign --armor appveyor.yml &&
    gem install octokit --no-document &&
    ruby deploy.rb create_release appveyor.yml* )

# Provide the rubyinstaller.exe files for download
artifacts:
  - path: appveyor.yml*
    name: Testfile

environment:
  GPGPASSWD:
    secure: /DELcKSZC+R4HdXgsqR1RtC+IrDZ3Xut/vzV/KgepE3M8OsjJtmWutN0+Jvc2Iv2
  DEPLOY_REPO_NAME: larskanis/ri2-deploy-test
  DEPLOY_TOKEN:
    secure: HIQ7Ovn+zMKskPWhnlYGvQMvdLPlZB5lhn62wzw0AUSno8UfntuTgFmPvS1pUwOW
